# Build docker image and deploy to google cloud run
name: cloud_deploy

on:
  push:
    branches:
      - feat/deploy-gh-action
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: opencdms-components-api
  REGION: europe-west1
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/opencdms-components-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: idems/opencdms-components-api

      # authenticate to google cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{secrets.GCP_SA_KEY_B64}}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.IMAGE_NAME}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}, mode=max

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
