# https://docs.docker.com/ci-cd/github-actions/

name: docker_build

on:
  push:
    branches:
      - "feat/docker-build-gh"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: echo "Building docker image ${{ secrets.DOCKER_HUB_USERNAME }}/opencdms-components-server-demo:${{github.sha}}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/opencdms-components-server-demo:${{github.sha}}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/opencdms-components-server-demo:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/opencdms-components-server-demo:buildcache,mode=max
